#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
lofo_from_bundle.py

Out-of-the-box:
  python analysis/lofo_from_bundle.py

Reads (default):
  <repo>/data/qnm/qnm_kerr_bundle_enriched.csv
Fallback:
  <repo>/data/qnm/qnm_kerr_bundle.csv  (BUT must contain Delta/THM/R; normally you run enrich first)

Writes:
  <repo>/figures/qnm_ratio_collapse/lofo_unique_table.tex
  <repo>/figures/qnm_ratio_collapse/lofo_unique_summary.json

Meaning:
  LOFO over UNIQUE families keyed by (ell,m,n,source) by default.
  For each leave-one-family-out, report median R over Delta <= delta_max.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple

import numpy as np
import pandas as pd


CAND_R = ["R", "ratio", "R_ratio"]
CAND_DELTA = ["Delta", "delta", "Δ", "one_minus_chi2", "1-chi^2"]


def find_repo_root(start: Path) -> Path:
    start = start.resolve()
    for d in [start] + list(start.parents):
        if (d / "analysis").is_dir() and (d / "data").is_dir():
            return d
    return Path.cwd().resolve()


def _require_col(df: pd.DataFrame, candidates: List[str], label: str) -> str:
    for c in candidates:
        if c in df.columns:
            return c
    raise KeyError(
        f"Cannot find required column for '{label}'. Tried candidates: {candidates}. "
        f"Available columns: {list(df.columns)}"
    )


def _safe_mkdir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="LOFO unique-family table for near-extremal Kerr QNM ratio R.")
    p.add_argument("--in", dest="input_csv", default=None, help="Input enriched CSV (default: data/qnm/qnm_kerr_bundle_enriched.csv)")
    p.add_argument("--outdir", default=None, help="Output dir (default: figures/qnm_ratio_collapse)")
    p.add_argument("--delta_max", type=float, default=0.05, help="Filter Delta <= delta_max (default: 0.05)")
    p.add_argument("--family_key", default="ell,m,n,source", help="Comma-separated key columns (default: ell,m,n,source)")
    p.add_argument("--digits", type=int, default=17, help="Digits to print in LaTeX (default: 17)")
    return p.parse_args()


def _format_float(x: float, digits: int) -> str:
    if np.isnan(x):
        return "nan"
    return f"{x:.{digits}g}"


def make_lofo_unique(input_csv: Path, out_dir: Path, delta_max: float, family_key: List[str], digits: int) -> Dict[str, Any]:
    df = pd.read_csv(input_csv)

    delta_col = _require_col(df, CAND_DELTA, "Delta")
    r_col = _require_col(df, CAND_R, "R")

    for c in family_key:
        if c not in df.columns:
            raise KeyError(f"Missing family key column '{c}'. Available: {list(df.columns)}")

    df[delta_col] = pd.to_numeric(df[delta_col], errors="coerce")
    df[r_col] = pd.to_numeric(df[r_col], errors="coerce")

    df = df.dropna(subset=[delta_col, r_col] + family_key).copy()
    df_f = df[df[delta_col] <= float(delta_max)].copy()

    filtered_N = int(len(df_f))
    if filtered_N == 0:
        raise SystemExit(f"[error] after filtering Delta <= {delta_max}, no rows remain")

    # Identify unique families
    fam_df = df_f[family_key].drop_duplicates().reset_index(drop=True)

    # Baseline (no drop)
    base_med = float(np.median(df_f[r_col].to_numpy()))

    rows = [{"label": f"none (full sample, $\\Delta\\le{delta_max}$)", "median": base_med}]

    # LOFO: drop each family
    for _, fam in fam_df.iterrows():
        mask = np.ones(len(df_f), dtype=bool)
        for k in family_key:
            mask &= (df_f[k].to_numpy() == fam[k])
        df_drop = df_f.loc[~mask]
        med = float(np.median(df_drop[r_col].to_numpy())) if len(df_drop) else float("nan")

        # label format: drop (ell,m,n)=(... ) [source]
        if set(["ell", "m", "n"]).issubset(set(family_key)):
            triple = (int(fam["ell"]), int(fam["m"]), int(fam["n"]))
            src = str(fam["source"]) if "source" in family_key else "family"
            label = rf"drop (\ell,m,n)=({triple[0]},{triple[1]},{triple[2]}) [{src}]"
        else:
            kv = ", ".join([f"{k}={fam[k]}" for k in family_key])
            label = f"drop {kv}"
        rows.append({"label": label, "median": med})

    # Write LaTeX
    tex_path = out_dir / "lofo_unique_table.tex"
    with tex_path.open("w", encoding="utf-8") as f:
        f.write("% Auto-generated by analysis/lofo_from_bundle.py\n")
        f.write("\\begin{tabular}{ll}\n")
        f.write("\\toprule\n")
        f.write("LOFO subset & median $R$ \\\\\n")
        f.write("\\midrule\n")
        for r in rows:
            f.write(f"{r['label']} & {_format_float(float(r['median']), digits)} \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")

    summary = {
        "input": str(input_csv),
        "delta_max": float(delta_max),
        "filtered_N": filtered_N,
        "family_key": family_key,
        "digits_used": int(digits),
        "rows": rows,
    }
    (out_dir / "lofo_unique_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def main() -> None:
    args = parse_args()
    root = find_repo_root(Path(__file__).resolve())

    input_csv = Path(args.input_csv) if args.input_csv else (root / "data" / "qnm" / "qnm_kerr_bundle_enriched.csv")
    out_dir = Path(args.outdir) if args.outdir else (root / "figures" / "qnm_ratio_collapse")
    _safe_mkdir(out_dir)

    if not input_csv.exists():
        raise SystemExit(
            f"[error] input not found: {input_csv}\n"
            f"        Run first: python analysis/enrich_qnm_bundle.py"
        )

    family_key = [s.strip() for s in str(args.family_key).split(",") if s.strip()]
    summary = make_lofo_unique(
        input_csv=input_csv,
        out_dir=out_dir,
        delta_max=float(args.delta_max),
        family_key=family_key,
        digits=int(args.digits),
    )

    print(f"[ok] read : {input_csv}")
    print(f"[ok] wrote: {out_dir / 'lofo_unique_table.tex'}")
    print(f"[ok] wrote: {out_dir / 'lofo_unique_summary.json'}")
    print(f"[info] filtered N={summary['filtered_N']} (Delta <= {summary['delta_max']})")
    print(f"[info] digits_used={summary['digits_used']}")


if __name__ == "__main__":
    main()